---
- hosts: frontend
  gather_facts: no
  roles:
    - ubuntu-16-04

  tasks:
    - name: Build the application
      shell: ./scripts/build-web-ui.sh
      delegate_to: 127.0.0.1

    - name: Upload the application
      synchronize:
        src: web.zip
        dest: web.zip

    - name: Copy the site config
      become: yes
      copy:
        src: config/beta.xsnexplorer.io
        dest: /etc/nginx/sites-available/beta.xsnexplorer.io

    - name: Enable the site
      become: yes
      file:
        src: /etc/nginx/sites-available/beta.xsnexplorer.io
        dest: /etc/nginx/sites-enabled/beta.xsnexplorer.io
        state: link

    - name: Create the web data directory
      become: yes
      file:
        path: /var/www/beta
        state: directory
        owner: www-data
        group: www-data

    - name: Unpack the application
      become: yes
      unarchive:
        remote_src: yes
        src: web.zip
        dest: /var/www/beta

    - name: Move the web content
      become: yes
      raw: rsync -a /var/www/beta/dist/ /var/www/beta/ --remove-source-files

    - name: Set the permissions
      become: yes
      file:
        dest: /var/www/beta
        owner: www-data
        group: www-data
        recurse: yes

    - name: Reload nginx config
      become: yes
      service:
        name: nginx
        state: reloaded
